# Generated by Django 4.2.23 on 2025-06-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cart_product_price_order_cart_product_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
