# Generated by Django 4.2.23 on 2025-06-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_checkoutinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutInfo',
        ),
    ]
