# Generated by Django 4.2.23 on 2025-06-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_checkoutinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
