# Generated by Django 4.2.23 on 2025-06-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_created_at',
            new_name='order_at',
        ),
    ]
