# Generated by Django 4.2.23 on 2025-06-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_order_created_at_order_order_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_at',
            new_name='ordered_at',
        ),
    ]
