# Generated by Django 4.2.23 on 2025-06-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_order_at_order_ordered_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
