# Generated by Django 4.2.23 on 2025-06-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_order_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
