# Generated by Django 4.2.23 on 2025-06-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_order_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
