# Generated by Django 4.2.23 on 2025-06-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
