# Generated by Django 4.2.23 on 2025-06-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
